### ISSUE TITLE
SWC extension doesn't seem to allow me to specify a .swcrc file

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp-extensions#10]
A simple chomp task where I run the SWC CLI directly works and picks up my .swcrc file:

```toml
[[task]]
name = 'build'
run = 'swc clients -d server/ssr/dist'
```

But trying to use the SWC extension, the .swcrc file seems to have no effect: 

The templated task looks like this:

```toml
[[task]]
name = 'build:js'
template = 'swc'
target = 'server/react/dist/##.js'
deps = ['clients/##.js']
[task.template-options]
config-file = '.swcrc'
```

Ejecting the task, the result is this:

```toml
[[task]]
name = 'build:js'
targets = ['server/react/dist/##.js']
deps = [
    'clients/##.js',
    'npm:install',
]
stdio = 'stderr-only'
run = 'node ./node_modules/@swc/cli/bin/swc.js $DEP -o $TARGET --no-swcrc --config-file=.swcrc --source-maps -C jsc.parser.syntax=typescript -C jsc.parser.importAssertions=true -C jsc.parser.topLevelAwait=true -C jsc.parser.importMeta=true -C jsc.parser.privateMethod=true -C jsc.parser.dynamicImport=true -C jsc.target=es2016 -C jsc.experimental.keepImportAssertions=true'
```

It looks like the `--no-swcrc` arg is passed even though I specify a `swcrc` file. This seems like it may be an error to me, and results in the `swcrc` file not being used
