### ISSUE TITLE
JSPM extension produces incorrect HTML in some cases

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp-extensions#12]
**Input HTML**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>A Title</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>
```

**Output HTML**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>False Bay forecast</title>
</head>
<body>
  <div id="root"></div>
</body>
</html<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
<script async src="https://ga.jspm.io/npm:es-module-shims@1.5.4/dist/es-module-shims.js" crossorigin="anonymous"></script>
<script type="importmap">
{}
</script>>
```

**Chomp task**
```toml
[[task]]
name = 'jspm'
dep = 'clients/pages/#/index.html'
target = 'server/ssr/dist/pages/#/index.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = false
```
