### ISSUE TITLE
Is it possible to configure environment variables at runtime?

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp-extensions#13]
Hi,

When using a template such as this:

```toml
[[task]]
name = 'jspm:node'
dep = '.cache/index.algoa-bay-forecast.js'
target = 'node.importmap'
template = 'jspm'
[task.template-options]
env = ['node', 'development', 'module']
```

I would like to configure the `env` at runtime:

```sh
ENV=development chomp jspm:node
# or
ENV=production chomp jspm:node
```

Then I would like to be able to use that environment variable - something along the lines of:

```sh
[[task]]
name = 'jspm:node'
dep = '.cache/index.algoa-bay-forecast.js'
target = 'node.importmap'
template = 'jspm'
[task.template-options]
env = ['node', '$ENV', 'module']
```

Sorry if this is possible already - if so I didn't see it in the docs

**Comment by guybedford** [comment]
Because all Chomp tasks are designed to be cached, it is important that they don't depend on out-of-band variations. Passing dynamic options to tasks means the cache is no longer reliable and would need to be keyed by that option, and then you need a whole custom cache structure which gets away from the simplicity of Chomp.

So because Chomp wants to know that if the dep hasn't changed, it can trust the previous run, this isn't really recommended, although there is actually an undocumented technique to pass custom arguments in:

```toml
[[task]]
name = 'jspm:node'
dep = '.cache/index.algoa-bay-forecast.js'
target = 'node.importmap'
template = 'jspm'
args = ['CONDITION']
```

will support `chomp jspm:node X` passing the `$CONDITION` environment variable based on the value `X`.

You'd then need to eject the JSPM template and reference the environment variable via `process.env.CONDITION` in the Node.js JSPM task body. But again this is not recommended and will likely be removed.

Rather I would suggest just having two separate tasks, corresponding to different development and production import maps to create invariance.
